# Generated by Django 5.2.6 on 2025-10-28 23:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0006_alter_bus_bus_number'),
        ('busminders', '0002_busminder_phone_number_busminder_status'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('drivers', '0002_driver_license_expiry_driver_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('driver_to_bus', 'Driver to Bus'), ('minder_to_bus', 'Bus Minder to Bus'), ('child_to_bus', 'Child to Bus'), ('bus_to_route', 'Bus to Route'), ('driver_to_route', 'Driver to Route'), ('minder_to_route', 'Bus Minder to Route'), ('child_to_route', 'Child to Route')], help_text='Type of assignment being made', max_length=20)),
                ('assignee_object_id', models.PositiveIntegerField(help_text='ID of the entity being assigned')),
                ('assigned_to_object_id', models.PositiveIntegerField(help_text='ID of the entity being assigned to')),
                ('effective_date', models.DateField(default=django.utils.timezone.now, help_text='When this assignment becomes effective')),
                ('expiry_date', models.DateField(blank=True, help_text='When this assignment expires (null = permanent)', null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When this assignment was created')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='active', help_text='Current status of this assignment', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for this assignment')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this assignment')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(help_text='User who made this assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to_content_type', models.ForeignKey(help_text='Type of entity being assigned to (Bus, Route, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_assignments', to='contenttypes.contenttype')),
                ('assignee_content_type', models.ForeignKey(help_text='Type of entity being assigned (Driver, Child, Bus, etc.)', on_delete=django.db.models.deletion.CASCADE, related_name='assignee_assignments', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], help_text='Action performed on the assignment', max_length=20)),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='When this action was performed')),
                ('changes', models.JSONField(default=dict, help_text='Details of what changed')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this change')),
                ('assignment', models.ForeignKey(help_text='The assignment this history entry refers to', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='assignments.assignment')),
                ('performed_by', models.ForeignKey(help_text='User who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment History',
                'verbose_name_plural': 'Assignment Histories',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Route name (e.g., 'Route A - Downtown Elementary')", max_length=100)),
                ('route_code', models.CharField(help_text="Unique route identifier (e.g., 'ROUTE_A')", max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the route')),
                ('schedule', models.JSONField(blank=True, default=dict, help_text='Route schedule with pickup/dropoff times in JSON format')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Estimated route duration in minutes', null=True)),
                ('total_distance', models.FloatField(blank=True, help_text='Total route distance in kilometers', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this route currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bus', models.ForeignKey(blank=True, help_text='Default bus assigned to this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_routes', to='buses.bus')),
                ('default_driver', models.ForeignKey(blank=True, help_text='Default driver assigned to this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_routes', to='drivers.driver')),
                ('default_minder', models.ForeignKey(blank=True, help_text='Default bus minder assigned to this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_routes', to='busminders.busminder')),
            ],
            options={
                'verbose_name': 'Bus Route',
                'verbose_name_plural': 'Bus Routes',
                'ordering': ['route_code'],
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignment_type', 'status'], name='assignments_assignm_5257ad_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['effective_date', 'expiry_date'], name='assignments_effecti_6b507a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assignee_content_type', 'assignee_object_id'], name='assignments_assigne_955902_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_to_content_type', 'assigned_to_object_id'], name='assignments_assigne_0b9203_idx'),
        ),
    ]
