# Generated by Django 5.2.6 on 2025-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busminder',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='busminder',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
