# Generated by Django 5.2.6 on 2025-10-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('parent', 'Parent'), ('busminder', 'Bus Minder'), ('driver', 'Driver'), ('admin', 'Admin')], max_length=20),
        ),
    ]
