# Generated by Django 5.2.6 on 2025-10-01 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.AddField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'driver'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_buses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='heading',
            field=models.FloatField(blank=True, help_text='Direction in degrees (0-360)', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is bus currently on route?'),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last GPS update timestamp'),
        ),
        migrations.AddField(
            model_name='bus',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude coordinate', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='speed',
            field=models.FloatField(blank=True, help_text='Current speed in km/h', null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
