# Generated by Django 5.2.6 on 2025-10-02 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_bus_options_bus_driver_bus_heading_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_minder',
            field=models.ForeignKey(blank=True, help_text='Bus minder responsible for this bus', limit_choices_to={'user_type': 'busminder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_buses', to=settings.AUTH_USER_MODEL),
        ),
    ]
