# Generated by Django 5.2.6 on 2025-10-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_bus_bus_minder'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=40, help_text='Maximum number of children'),
        ),
    ]
