# Generated by Django 5.2.6 on 2025-10-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_bus_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(default=0, help_text='Bus identification number', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bus',
            name='last_maintenance',
            field=models.DateField(blank=True, help_text='Last maintenance date', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='model',
            field=models.CharField(blank=True, help_text='Bus model/make', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='year',
            field=models.IntegerField(blank=True, help_text='Manufacturing year', null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='number_plate',
            field=models.CharField(help_text='License plate number', max_length=20, unique=True),
        ),
    ]
