# Generated by Django 5.2.6 on 2025-10-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_bus_bus_number_bus_last_maintenance_bus_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='bus_number',
            field=models.CharField(help_text='Bus identification number', max_length=20),
        ),
    ]
