# Generated by Django 5.2.6 on 2025-10-02 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0003_bus_bus_minder'),
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_on_bus', 'Not on Bus'), ('on_bus', 'On the way to school'), ('at_school', 'At School'), ('on_way_home', 'On the way home'), ('dropped_off', 'Dropped Off'), ('absent', 'Absent')], default='not_on_bus', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes from bus minder')),
                ('bus', models.ForeignKey(blank=True, help_text='Bus assigned to this child for this attendance record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='buses.bus')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='children.child')),
                ('marked_by', models.ForeignKey(blank=True, help_text='Bus minder who marked this attendance', limit_choices_to={'user_type': 'busminder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-timestamp'],
                'unique_together': {('child', 'date')},
            },
        ),
    ]
