# Generated by Django 5.2.6 on 2025-10-04 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0006_alter_bus_bus_number'),
        ('children', '0002_child_age_child_status_alter_child_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(help_text='Route name/description', max_length=255)),
                ('trip_type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff')], default='pickup', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled departure time')),
                ('start_time', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='Actual completion time', null=True)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current GPS latitude', max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current GPS longitude', max_digits=9, null=True)),
                ('location_timestamp', models.DateTimeField(blank=True, help_text='Last location update time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(help_text='Bus assigned to this trip', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.bus')),
                ('bus_minder', models.ForeignKey(blank=True, help_text='Bus minder assigned to this trip', limit_choices_to={'user_type': 'busminder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minder_trips', to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(blank=True, help_text='Children assigned to this trip', related_name='trips', to='children.child')),
                ('driver', models.ForeignKey(help_text='Driver assigned to this trip', limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Stop address', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Stop GPS latitude', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Stop GPS longitude', max_digits=9)),
                ('scheduled_time', models.DateTimeField(help_text='Scheduled arrival time')),
                ('actual_time', models.DateTimeField(blank=True, help_text='Actual arrival time', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Order of this stop in the route')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('children', models.ManyToManyField(blank=True, help_text='Children to pickup/dropoff at this stop', related_name='trip_stops', to='children.child')),
                ('trip', models.ForeignKey(help_text='Trip this stop belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Stop',
                'verbose_name_plural': 'Stops',
                'ordering': ['trip', 'order'],
            },
        ),
    ]
