# Generated by Django 5.2.6 on 2025-10-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='parent',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
