# Generated by Django 5.2.6 on 2025-10-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_parent_address_parent_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
