# Generated by Django 5.2.6 on 2025-10-04 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('super-admin', 'Super Admin'), ('admin', 'Admin'), ('viewer', 'Viewer')], default='admin', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
